theme: jekyll-theme-minimal
title: Fortio (Φορτίο)
description: Fortio is a microservices (http, grpc) load testing library, command line tool, advanced echo server, and web UI in go (golang). Fortio allows to specify a set query-per-second load and record latency histograms and other useful stats.
logo: fortio-logo-color.png
google_analytics: UA-124363339-1
show_downloads: false
github.is_project_page: false

gems:
  - jekyll-redirect-from

